title: Med-eQuip Consulting
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Right Device for the Right Price
url: "https://medequipconsulting.com" # the base hostname & protocol for your site, e.g. http://example.com
instagram: https://www.instagram.com/qburgessmedequip/
linkedin: https://www.linkedin.com/company/med-equip-consulting
